### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by xXZaretXx** [bumbummen99/southparkdownloader#13] opened 2021-05-07 16:37 UTC
Hi, 
i am the only one where youtube-dl(c) failed to download?

YoutubeDL failed
no videos to merge

also the normal way with youtube-dl failes `youtube-dl "https://www.southpark.de/folgen/jiru42/south-park-verkabelung-staffel-23-ep-9"
ERROR: Unsupported URL: https://www.southpark.de/folgen/jiru42/south-park-verkabelung-staffel-23-ep-9

**Comment by bumbummen99** [comment] 2021-05-07 16:57
Yep, i can confirm that with the latest youtube-dl and the latest youtube-dlc there is no compatiblity with southpark.de.
I wonder how this just broke again.

**Comment by okh-mzny** [comment] 2021-05-25 11:56
ytdl resorts to the [generic] extractor meaning that there was no successful regex match (that's how ytdl picks the right extractor for a site)
I'll look into how this can be fixed, and see if it gets first merged into ytdl or ytdlc :')

**Comment by KatzeMau** [comment] 2021-06-06 21:05
Can i just use the old version ?

**Comment by bumbummen99** [comment] 2021-06-07 06:42
> Can i just use the old version ?

Sadly no. YouTube DL does have to be compatible the current, actual version of the website it does try to download from as there are no old version of that. I think, right now there is not much we can do about it other than contribute to YouTube-DL to fix it or find another, mor stable solution to downloading the parts off of southpark.de (and .com prefferably).

Maybe, if it is a simple fix, we could create a custom fork & build of ytdl for this tool.

**Comment by xXZaretXx** [comment] 2021-06-07 08:10
There is already an working fork/issue for this on youtube-dl
https://github.com/ytdl-org/youtube-dl/pull/28442
If you check out and compile your own youtube-dl version, it works.. Don't ask me how to compile it to an windows exe... but the linux executable works with southpark.de .. it's just an simple change in the url from files.. thats because the actual and old versions didn't work

**Comment by yulez7** [comment] 2021-08-05 17:16
xXZaretXx how did you start the linux aplication? im new to linux and the command doesnt do anything 
youtube-dl is working on my ubuntu VM 
Thanks for the help :)

**Comment by xXZaretXx** [comment] 2021-08-05 17:50
> xXZaretXx how did you start the linux aplication? im new to linux and the command doesnt do anything
> youtube-dl is working on my ubuntu VM
> Thanks for the help :)

Thats not the point about this issue ^^ , but okay, you need to set the execution bit on SouthparkDLCommandLine (chmod +x SouthParkDLCommandline)  and then just simple  type ./SouthParkDLCommandLine in your prefered terminal.. you need to be in thie correct directory . thats all to open the terminal application

**Comment by yulez7** [comment] 2021-08-05 18:39
@xXZaretXx I know thats not the issue :D i got youtube dl working for southpark.de 
could you explain it a bit better for a dummi like me :D?

**Comment by PPrzemko** [comment] 2021-08-11 20:43
I could not get it to work with newest Youtube-dl source. Still "No video files to merge!"

**Comment by bumbummen99** [comment] 2021-12-07 19:59
Looks like it is fixed, i will try in the following day and update if necessary

**Comment by bumbummen99** [comment] 2023-03-06 23:34
## Repository Deprecated Notice

This repository is no longer maintained. All issues, including this one, will be closed.

Please visit [the repository](https://github.com/bumbummen99/southpark-downloader) to access the new version of SouthPark Downloader.

For an in-depth explanation on why this repository has been deprecated, please refer to the [Readme.md](https://github.com/bumbummen99/southparkdownloader#important-notice).

**Closed as completed by bumbummen99** 2023-03-06 23:34 UTC
